services:
  db:
    image: postgres:latest
    container_name: kanban
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - kanban-data:/var/lib/postgresql
volumes:
  kanban-data: